### ISSUE TITLE
Daw integration?

### ISSUE THREAD

**Issue by Zetalia** [satelllte/adsr#92]
Hello satellite, 

thank you for this little gem, i like the sound a lot.
Would be even better with a bit of saturation etc... 
is there a way to integreate it into vst au m4l...?

**Comment by satelllte** [comment]
Hi @Zetalia. This thing is built specifically to try out Elementary Audio, the web platform was just the easiest option. I don't have any plans on integrating it into other platforms, but you can fork it and try if you want.

This can be a good starting point example for Elementary + JUCE integration, I believe: https://github.com/elemaudio/srvb.

**Comment by Zetalia** [comment]
thank you for the reply, i was thinking to have a look but right now i am deep diving into Max, so there is not much brainpower left for sideprojects. ill check elemental audio when the max fever cools down a bit, thank you.
